version: '{build}'

environment:
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  GOPATH: C:\gopath
  GOROOT: C:\go\
  GOVERSION: 1.11

install:
  - ps: choco install ant
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - cmd: SET PATH=%GOPATH%\bin;%GOPATH%\bin\windows_386;%GOROOT%bin;%PATH%
  - java -version
  - ant -version
  - go version
  - go env

configuration:
  - Release

build_script:
  - ant release

after_build:
  - ps: |
      $env:APP_VERSION = Get-Content "$env:APPVEYOR_BUILD_FOLDER\bin\tmp\version.dat" -Raw
      Write-Host "App version: $env:APP_VERSION"

artifacts:
  - path: 'bin\release\*'
    name: release

deploy:
  tag: $(APP_VERSION)
  release: $(APP_VERSION)
  description: 'New release: $(APP_VERSION)'
  provider: GitHub
  auth_token:
    secure: BGz5Z+cKh7a/UOFxIfBfZYho8Ghf3bO3LvaX70mdgiG1UDJhtW3FUGDjBrwyZglf
  artifact: release
  draft: true
  prerelease: false
  on:
    branch: master

notifications:
  - provider: Webhook
    url:
      secure: Vf+59lgCDVyte9kmHKwYXPR7uc6THo9IH6mQwiPAWOCQHUoLCQrGFupj30nk4MUggyWss3ydobo/z1sQ6iYabwAkkwI6H9XNmjgGgTVlCJoBISHN6yTwxLgkYMi40qT4Mevr9XVgd6EmJqOi257YjQ==
    method: post
